import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './app/components/**/*.{js,vue,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/plugins/**/*.{js,ts}',
    './app/app.vue',
    './app/error.vue',
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          DEFAULT: 'var(--color-bg)',
          muted: 'var(--color-bg-muted)',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          highlight: 'var(--color-surface-highlight)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          glow: 'var(--color-border-glow)',
        },
        divider: 'var(--color-divider)',
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          muted: 'var(--color-text-muted)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          soft: 'var(--color-accent-soft)',
          strong: 'var(--color-accent-strong)',
          glow: 'var(--color-accent-glow)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          soft: 'var(--color-secondary-soft)',
          glow: 'var(--color-secondary-glow)',
        },
        positive: {
          DEFAULT: 'var(--color-positive)',
          soft: 'var(--color-positive-soft)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          soft: 'var(--color-warning-soft)',
        },
        critical: {
          DEFAULT: 'var(--color-critical)',
          soft: 'var(--color-critical-soft)',
        },
        neon: {
          cyan: 'var(--neon-cyan)',
          'cyan-bright': 'var(--neon-cyan-bright)',
          purple: 'var(--neon-purple)',
          'purple-bright': 'var(--neon-purple-bright)',
          pink: 'var(--neon-pink)',
          'pink-bright': 'var(--neon-pink-bright)',
          green: 'var(--neon-green)',
          'green-bright': 'var(--neon-green-bright)',
          orange: 'var(--neon-orange)',
          'orange-bright': 'var(--neon-orange-bright)',
          blue: 'var(--neon-blue)',
          'blue-bright': 'var(--neon-blue-bright)',
          yellow: 'var(--neon-yellow)',
          'yellow-bright': 'var(--neon-yellow-bright)',
          red: 'var(--neon-red)',
          'red-bright': 'var(--neon-red-bright)',
          teal: 'var(--neon-teal)',
          'teal-bright': 'var(--neon-teal-bright)',
          lime: 'var(--neon-lime)',
          'lime-bright': 'var(--neon-lime-bright)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
      },
      spacing: {
        'space-1': 'var(--space-1)',
        'space-2': 'var(--space-2)',
        'space-3': 'var(--space-3)',
        'space-4': 'var(--space-4)',
        'space-5': 'var(--space-5)',
        'space-6': 'var(--space-6)',
        'space-7': 'var(--space-7)',
        'space-8': 'var(--space-8)',
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        'glow-accent': 'var(--glow-accent)',
        'glow-secondary': 'var(--glow-secondary)',
        'glow-positive': 'var(--glow-positive)',
        'glow-x': 'var(--glow-x)',
        'glow-o': 'var(--glow-o)',
        'glow-square': 'var(--glow-square)',
        'glow-star': 'var(--glow-star)',
        'glow-triangle': 'var(--glow-triangle)',
        'glow-diamond': 'var(--glow-diamond)',
        'glow-circle': 'var(--glow-circle)',
        'glow-plus': 'var(--glow-plus)',
        'glow-heart': 'var(--glow-heart)',
        'glow-pentagon': 'var(--glow-pentagon)',
      },
      transitionTimingFunction: {
        base: 'cubic-bezier(0.4, 0, 0.2, 1)',
        bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
      transitionDuration: {
        base: '200ms',
        slow: '350ms',
        bounce: '400ms',
      },
      animation: {
        'winning-pulse': 'winningPulse 1.5s ease-in-out infinite',
        'cell-appear': 'cellAppear 0.4s ease-out forwards',
        'selected-pulse': 'selectedCellPulse 1.5s ease-in-out infinite',
        'active-player-pulse': 'activePlayerPulse 2s ease-in-out infinite',
        'grid-pulse': 'gridPulse 4s ease-in-out infinite',
        'icon-pulse': 'iconPulse 2s ease-in-out infinite',
        'gradient-shift': 'gradientShift 15s ease infinite',
      },
    },
  },
  plugins: [],
} satisfies Config
